### ISSUE TITLE
First Version of SRL-JavaScript

### ISSUE THREAD

**Issue by teabyii** [SimpleRegex/SRL-JavaScript#1]
I have made first version of the implementation of [SRL-JavaScript](https://github.com/SimpleRegex/SRL-JavaScript).

Things that have already been done:
- Builder
- Interpreter to compile DSL to builder.
- Test Rules
- NPM package: [SRL](https://www.npmjs.com/package/srl)

There is something different from [SRL-PHP](https://github.com/SimpleRegex/SRL-PHP):
- NOT support `as` to assign capture name. 
- NOT support `if already had/if not already had` 
- NO `firstMatch`, since in JavaScript `lazy` means non-greedy (matching the fewest possible characters).

**Comment by KarimGeiger** [comment]
First of all: Great work. Thanks a lot for your effort. The incompatibilities listed aren't a problem since they're language specific.

But there's one thing I've noticed. Correct me if I'm wrong, but I can't see the `Rules` tests being executed on Travis: https://travis-ci.org/SimpleRegex/SRL-JavaScript

**Comment by teabyii** [comment]
It's a problem, I will check it.

**Comment by teabyii** [comment]
Just forgot to print results of the rules test, fixed: #2 .

**Comment by KarimGeiger** [comment]
Looks good now. I'll link to this repository from the official website as soon as I'm at home.

**Comment by teabyii** [comment]
👍
